package com.loopers.domain.notification;

public enum NotificationType {
    APPOINTMENT_INVITE,
    APPOINTMENT_UPDATED,
    APPOINTMENT_CANCELLED,
    FRIEND_REQUEST,
    FRIEND_ACCEPTED,
    NUDGE,
    TRAVEL_TIME_CHANGED,
    DEPARTURE_REMINDER,
    APPOINTMENT_REMINDER,
    DEPARTURE_LOCATION_MISSING
}
